apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://zabbix-web:8080/api_jsonrpc.php
    isDefault: true
    jsonData:
      username: Admin
      zabbixVersion: 5.0.x
      trendsFrom: "7d"
      trendsRange: "4d"
    secureJsonData:
      password: zabbix